language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - pip install --use-mirrors pytest mock coveralls pytest-cov

script:
  - py.test --cov echo test_echo.py

after_success:
  - coveralls
